### ISSUE TITLE
[Request] Japanese translation

### ISSUE THREAD

**Issue by arairait** [mkopec/close-tabs-to-the-left#12]
I would appreciate it if you would add Japanese translation.
For your help, here is messages.json for Japanese ("ja" folder).

[messages.json.txt](https://github.com/mkopec/close-tabs-to-the-left/files/1590564/messages.json.txt)

Regards,

**Comment by piroor** [comment]
Oops, after I created the PR #13, I've noted that this issue is already opened. My version is different from your version on some points:

 * I didn't translate the name of the extension, for findability.
 * My version of the description is a word-for-word translation.

**Comment by arairait** [comment]
Thank you for your PR.
The contextItemTitle message which users usually take a look is the same as my one,
the translation is no problem.👍 
I hope your PR will be merged.

**Comment by mkopec** [comment]
Merged #13, issue resolved.
