### ISSUE TITLE
Move to "close Multiple tabs" menu

### ISSUE THREAD

**Issue by zeitounator** [mkopec/close-tabs-to-the-left#17]
In latest firefox, multiple tab closing options have been grouped as submenus of "Close Multiple tabs".

Is it possible to move the "close tab to the left" entry there ?

Thanks.

**Comment by Beatusvir** [comment]
Came here for this, please move it so it matches other options!

**Comment by ashledombos** [comment]
Now close tabs to the left is native in Firefox.

**Comment by zeitounator** [comment]
@ashledombos thanks for reminding me I had that ticket opened ;) Extension removed a long while ago since it is not needed anymore.

@mkopec Thanks for providing this workaround while that function was not available.

Closing this as it is now totally irrelevant.

Cheers.
