### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by ghost** [mkopec/close-tabs-to-the-left#2]
Hi,
I just thought I'd add a Chinese translation. Sorry for the lack of a patch, but I haven't got time to set up git on my current machine atm.

For the context menu item, close tabs to the left should be "关闭左侧标签页“。This should also double as the translated name of the extension.

For the description it should be "在标签上下文菜单里插入关闭的左侧标签页的项目。"

Thanks,
Alex

**Comment by ghost** [comment]
I should also add a Taiwanese Translation.

Description: 在上下文菜單里插入關閉左側標籤頁的項目。

Context Menu and Name: 關閉左側標籤頁

**Comment by mkopec** [comment]
Done and done. Thank you!
